# Use an official Node.js image to serve the client app
FROM node:latest

# Set the working directory inside the container
WORKDIR /client

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install



# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app will run on (e.g., for React, it's usually 3000)
EXPOSE 3100

# Set environment variable for development
ENV NODE_ENV=development

# Command to start the app in development mode
CMD ["npm", "start"]