# Use an official Node.js image as the base image
FROM node:latest

# Set the working directory inside the container
WORKDIR /server

# Copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install the necessary dependencies
RUN npm install


# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app will run on
EXPOSE 3100

# Set an environment variable to differentiate between development and production
ENV NODE_ENV=development

# Command to start the application (could vary depending on your setup)
CMD ["npm" , "start"]